export const dados = [
  {
    id: 1,
    autor: "a",
    titulo: "Dom Quixote",
    tipo: "Aventura e Romance",
    lancamento: "1605",
    imagem:"",
  },
  {
    id: 2,
    autor: "a",
    titulo: "Memórias Póstumas de Bras Cúbas",
    tipo: "Romance",
    lancamento: "1881",
    imagem:"",
  },
  {
    id: 3,
    autor: "a",
    titulo: "Helena",
    tipo: "Romance",
    lancamento: "1876",
    imagem:"",
  },
  {
    id: 4,
    autor: "a",
    titulo: "Hora da Estrela",
    tipo: "Romance",
    lancamento: "1977",
    imagem:"",
  },
  {
    id: 5,
    autor: "a",
    titulo: "Harry Potter e a Pedra Filosofal",
    tipo: "Fantasia e Aventura",
    lancamento: "1997",
    imagem:"",
  },
  {
    id: 6,
    autor: "a",
    titulo: "A Divina Comédia",
    tipo: "Poesia",
    lancamento: "1321",
    imagem:"",
  },
]
